// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHuzooFnvZXSwurt7pJ2wpPNGBYLvak9U',
    appId: '1:189838799053:web:cb3641dba90877758c3984',
    messagingSenderId: '189838799053',
    projectId: 'money-manager-f6c8f',
    authDomain: 'money-manager-f6c8f.firebaseapp.com',
    storageBucket: 'money-manager-f6c8f.appspot.com',
    measurementId: 'G-WL6G1RGHMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkI1FG_8CFIssmsmB1oplyMtUiCiSzJcA',
    appId: '1:189838799053:android:cd78252d1e3143518c3984',
    messagingSenderId: '189838799053',
    projectId: 'money-manager-f6c8f',
    storageBucket: 'money-manager-f6c8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdjIIWA6cAwA4WRKCsgpOiB9-4p8qaNiU',
    appId: '1:189838799053:ios:36127ef04fdaf2b38c3984',
    messagingSenderId: '189838799053',
    projectId: 'money-manager-f6c8f',
    storageBucket: 'money-manager-f6c8f.appspot.com',
    iosClientId: '189838799053-tkec7gejggdsagejgnom8ieh105tu5b9.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdjIIWA6cAwA4WRKCsgpOiB9-4p8qaNiU',
    appId: '1:189838799053:ios:36127ef04fdaf2b38c3984',
    messagingSenderId: '189838799053',
    projectId: 'money-manager-f6c8f',
    storageBucket: 'money-manager-f6c8f.appspot.com',
    iosClientId: '189838799053-tkec7gejggdsagejgnom8ieh105tu5b9.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFlutterApp',
  );
}
